config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  resources :secrets,  only: [:index, :create, :show, :destroy]

  resources :likes,    only: [:create, :destroy]

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  has_many :users, through: :likes

  validates_presence_of :content, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  has_many :secrets
  has_many :likes, dependent: :destroy
  has_many :secrets_liked, through: :likes, source: :secret

  has_secure_password
  validates_presence_of :name
  # validates_presence_of :password, on: :create
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: EMAIL_REGEX }

  before_save { self.email.downcase! }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  def current_user
    User.find(session[:user_id]) if session.key?(:user_id)
    # session.key?(:user) ? User.find(session[:user]) : null
  end

  helper_method :current_user

  private

  def require_login
    # redirect_to new_session_path unless session.key?(:user_id)
    redirect_to new_session_path unless current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    secret = Secret.find(params[:secret_id])
    Like.create(user: current_user, secret:secret)

    return redirect_to secrets_path
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy

    return redirect_to secrets_path
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    @secrets = Secret.all
  end

  def create
    secret = Secret.create(content: params[:content], user: current_user)
    unless secret.valid?
      flash[:errors] = secret.errors.full_messages
      return redirect_to user_path current_user
    end
    return redirect_to user_path current_user
  end

  def destroy
    secret = Secret.find(params[:id])
    user = secret.user
    secret.destroy if user == current_user
    return redirect_to user_path user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email]).try(:authenticate, params[:password])
    if user
      session[:user_id] = user.id
      return redirect_to user_path user.id
    else
      flash[:errors] = ['Invalid Combination']
      return redirect_to new_session_path
    end
  end

  # #Better way
  # def create
  #   user = User.find_by_email(params[:email])
  #   if user
  #     if user.authenticate(parms[:password])
  #       session[:user] = user.id
  #       return redirect_to user_path user.id
  #     end
  #       flash[:errors] = ['Incorrect password']
  #   else
  #     flash[:errors] = ['Incorect email']
  #   end
  # end

  def destroy
    session.delete(:user_id) if session[:user_id]
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :authorized_user, except: [:index, :new, :create]

  def index
    redirect_to new_user_path
  end

  def new
  end

  def show
    @user = User.find(params[:id])
    @secrets = @user.secrets
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    user = User.create( user_params )
    unless user.valid?
      flash[:errors] = user.errors.full_messages
      return redirect_to new_user_path
    end
    return redirect_to new_session_path
  end

  def update
    user = User.find(params[:id])
    user.name = params[:name]
    user.email = params[:email]
    user.save
    unless user.valid?
      flash[:errors] = user.errors.full_messages
      return redirect_to :back
    end
    return redirect_to user_path user.id
  end

  def destroy
    User.find(params[:id]).destroy
    session.delete(:user_id) if session[:user_id]
    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def authorized_user
    user = User.find(params[:id])
    redirect_to user_path current_user unless user == current_user
    # Alternate way
    # user_id = params[:id].to_i
    # redirect_to "/users/#{current_user.id}" unless current_user.id == user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoSecrets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 mx-md-auto text-center">
        <%= render 'partials/navbar' %>
        <%= render 'partials/errors' %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/partials/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p class='text-danger'><%= error %></p>
  <% end %>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= secrets_path %>">Dojo Secrets</a>
      <% if current_user %>
        <a href="<%= session_path current_user%>" data-method='delete'>Logout</a>
        <a href="<%= secrets_path %>">View All Secrets</a>
        <a href="<%= user_path current_user %>">Dashboard</a>
      <% else %>
        <a href='<%= new_session_path %>'>Login</a>
        <a href='<%= new_user_path %>'>Register</a>
      <% end %>
    </div>
  </div>
</nav>

app/views/secrets/index.html.erb
<h2>All Secrets</h2>

<% @secrets.each do |secret| %>
  <p>
    <% if secret.users.include? current_user %>
      <a href="<%= like_path secret.likes.where(user: current_user).first.id %>" data-method='delete'>
        <button class="like_button btn btn-danger">Unlike</button>
      </a>
    <% else %>
      <form class='display_inline' action="<%= likes_path %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="secret_id" value="<%= secret.id %>">
        <input class='like_button btn btn-primary' type="submit" value="Like">
      </form>
    <% end %>
    <%= secret.content %>
    <span class='likes'>
      <%= secret.likes.count %>
      <%= secret.likes.count == 1 ? 'like' : 'likes' %>
    </span>
    <% if current_user == secret.user %>
      <a href="<%= secret_path secret %>" data-method= 'delete'>
        <button class='delete_button'>Delete Secret</button>
      </a>
    <% end %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %>'s Information</h2>
<form action="<%= user_path @user %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label for="name">Name</label>
  <input type="text" name="name" value='<%= @user.name %>'><br><br>

  <label for="email">Email</label>
  <input type="text" name="email" value='<%= @user.email %>'><br><br>

  <input type="submit" value="Update">
</form>

<a href="<%= user_path @user%>" data-method='delete'><button name="Delete">Delete</button></a>

app/views/users/new.html.erb
<h2>Registration</h2>
<form action="<%= users_path %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
  <input class='form-control' type="text" name="user[name]" placeholder='Name'><br><br>

  <label for="email">Email</label>
  <input class='form-control' type="email" name="user[email]" placeholder='Email'><br><br>

  <label for="password">Password</label>
  <input class='form-control' type="password" name="user[password]" placeholder='Password'><br><br>

  <label for="password_confirmation">Password Confirmation</label>
  <input class='form-control' type="password" name="user[password_confirmation]" placeholder='Password Confirmation'><br><br>

  <input class='btn btn-primary' type="submit" value="Register">
</form>

<p>Already a user? <a href='<%= new_session_path %>'><button>Log In</button></a></p>

app/views/users/show.html.erb
<h2><%= @user.name %>'s Information</h2>
<p><%= @user.email %></p>
<a href="<%= edit_user_path @user %>">Edit Profile</a><br><br>

<form action="<%= secrets_path %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Content</label><br />
  <!-- <input type="text" name="content"> -->
  <textarea name="content" rows="4" cols="40"
            placeholder="What's your secret?">
  </textarea><br>

  <input class='btn btn-primary' type="submit" name="submit" value="Create Secret">
</form>

<h3>My secrets</h3>
<% if @secrets %>
  <% @secrets.each do |secret| %>
    <p><%= secret.content %>
      <% if current_user == secret.user %>
        <a href="<%= secret_path secret %>" data-method= 'delete'>
          <button class='delete_button'>Delete Secret</button>
        </a>
      <% end %>
    </p>
  <% end %>
<% end %>